name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: openzim/docker-publish-action@main
        with:
          image-path: openzim/youtube
          on-master: dev
          tag-pattern: /^v([0-9.]+)$/
          latest-on-tag: true
          restrict-to: openzim/youtube
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}
